### ISSUE TITLE
cargo-px install fails because stdsimd feature has been removed

### ISSUE THREAD

**Issue by jreuben11** [LukeMathWalker/cargo-px#36]
tried running `cargo install --locked cargo-px`

got
```
error[E0635]: unknown feature `stdsimd`
  --> /home/jreuben1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.6/src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^
```

`rustc --version` ->    rustc 1.81.0-nightly (20ae37c18 2024-07-07)

apparently, The stdsimd feature was removed:
https://github.com/rust-lang/rust/commit/ea37e8091fe87ae0a7e204c034e7d55061e56790

**Comment by LukeMathWalker** [comment]
This should have been fixed in the latest release, via #37.
Thanks for reporting it!
